### PR TITLE
ShowChallongeHash

### PR DESCRIPTION
**Pull request by Camtendo**
In certain cases, we need the Challonge API hash (i.e. giving it to ReesayBot to talk to chat). This branch displays it easily next to the url after it is set so we don't have to manually evaluate it.

This branch also refactors `admin.hbs` a bit to have js functions in a separate file.

### CODE REVIEW

**Comment by dguenther** [comment]
What's the API hash for? Is it something that changes?

**Comment by dguenther** [comment]
Also :+1: to pulling all that JS out of the views!

**Comment by Camtendo** [comment]
The API hash is unique for every Challonge URL. If we change brackets mid-tournament, it will change.

**Comment by dguenther** [comment]
Ahh, this is for pasting into reesaybot, got it. Merge time

**Pull request merged**
